kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-server-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: thin-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

# ---
#  kind: StorageClass
#  apiVersion: storage.k8s.io/v1
#  metadata:
#    name: thin-disk
#    annotations:
#      storageclass.kubernetes.io/is-default-class: "true"
#  provisioner: kubernetes.io/vsphere-volume
#  parameters:
#      diskformat: thin
#      datastore: KV1PRD_CONTAINER_L001_N01
